### ISSUE TITLE
Failing test_Masters_get_bnaseline_data()

### ISSUE THREAD

**Issue by yulqen** [banillie/analysis_engine#9]
We can look at this Thursday, but it looks pretty simple.  Change your test to:

```python
def test_Masters_get_baseline_data():
    mst = Masters(list_of_masters_all[1:], list_of_masters_all[1].projects)
    mst.get_baseline_data('Re-baseline IPDC milestones')
    assert isinstance(mst.bl_info, (dict,))
```
And the test passes. You were setting the output of `mst.get_baseline_data()` to a variabled called `bl`. `Masters.get_baseline_data()` does not return anything, therefore `bl` will always be set to `None`. In which case, your `assert` will fail.

Remember, the point about having methods on an object is really to set data on the object itself - i.e. you set the `self` attributes. That's what you're doing in lines 55 and 56 in `data_mgmt.data`.

Happy to explain Thursday!

**Comment by banillie** [comment]
Thanks Matt, I thought it might be something simple. Yes pls lets talk about it some more on Thursday. It would be useful to know when something is and isn't a method. 

How would you now pass a masters_object into another class. Does the mst.get_baseline_data('blah') need to be passed in separately, because bl_info and bl_index will be empty unless they are called?

**Comment by yulqen** [comment]
As ever, it all depends on what you want to do - and by asking these questions, you're working out what your the design should be for your code. There's never a final answer to that - it evolves. Great thing about what you're doing now, is learning enough to be able to ask these questions and ponder the possible options. Let's discuss tomorrow.

**Comment by banillie** [comment]
Excellent. Look forward to discussing. Love it! See you tomorrow.
